server:
  port: 8120 # 服务端口

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-oss # 服务名
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848  #微服务注册到Nacos 要注册成功必须引入Nacos依赖

aliyun:
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com
    keyid: LTAI5tDAJbmAGWqUZhyMKCtP
    keysecret: tJPxCbF666WNYMKb4zjnvd53Q3MUbA
    #bucket可以在控制台创建，也可以使用java代码创建，注意先测试bucket是否已被占用
    bucketname: avatar-college-file03

